// <auto-generated />
using System;
using Drill08.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Drill08.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Drill08.Entities.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FinalGrade")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingTrackId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TrainingTrackId");

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            EnrollmentId = 1,
                            CreatedAt = new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinalGrade = 100,
                            Status = "Active",
                            StudentId = 2,
                            TrainingTrackId = 1
                        },
                        new
                        {
                            EnrollmentId = 2,
                            CreatedAt = new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentDate = new DateTime(2026, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinalGrade = 90,
                            Status = "Active",
                            StudentId = 1,
                            TrainingTrackId = 2
                        },
                        new
                        {
                            EnrollmentId = 3,
                            CreatedAt = new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentDate = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinalGrade = 90,
                            Status = "Active",
                            StudentId = 1,
                            TrainingTrackId = 1
                        },
                        new
                        {
                            EnrollmentId = 4,
                            CreatedAt = new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinalGrade = 95,
                            Status = "Active",
                            StudentId = 3,
                            TrainingTrackId = 3
                        },
                        new
                        {
                            EnrollmentId = 5,
                            CreatedAt = new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinalGrade = 88,
                            Status = "Completed",
                            StudentId = 4,
                            TrainingTrackId = 2
                        });
                });

            modelBuilder.Entity("Drill08.Entities.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sama@gmail.com",
                            FullName = "Sama Samy"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sara@gmail.com",
                            FullName = "Sara Mohamed"
                        });
                });

            modelBuilder.Entity("Drill08.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentSummaryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaymentSummaryId");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("Drill08.Entities.PaymentSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("int");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalRequired")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EnrollmentId")
                        .IsUnique();

                    b.ToTable("PaymentSummaries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EnrollmentId = 1,
                            PaymentStatus = 1,
                            TotalPaid = 3000m,
                            TotalRequired = 5000m
                        },
                        new
                        {
                            Id = 2,
                            EnrollmentId = 2,
                            PaymentStatus = 2,
                            TotalPaid = 4000m,
                            TotalRequired = 4000m
                        });
                });

            modelBuilder.Entity("Drill08.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "rowida@gmail.com",
                            FullName = "Rowida Gamal",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "arwaa@gmail.com",
                            FullName = "Arwa Ali",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "gamal@gmail.com",
                            FullName = "Gamal Hassan",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hassan@gmail.com",
                            FullName = "Hassan Mohamed",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mona@gmail.com",
                            FullName = "Mona Ali",
                            IsActive = true,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("Drill08.Entities.StudentProfile", b =>
                {
                    b.Property<int>("NationalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NationalId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmergencyPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("NationalId");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("StudentProfiles");

                    b.HasData(
                        new
                        {
                            NationalId = 123456789,
                            Address = "Cairo",
                            DateOfBirth = new DateTime(2005, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmergencyPhone = "01122055628",
                            StudentId = 1
                        });
                });

            modelBuilder.Entity("Drill08.Entities.TrainingTrack", b =>
                {
                    b.Property<int>("TrackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrackId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("TrackName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("TrackId");

                    b.HasIndex("InstructorId");

                    b.ToTable("TrainingTracks");

                    b.HasData(
                        new
                        {
                            TrackId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = 1,
                            TrackName = "ASP.NET Core"
                        },
                        new
                        {
                            TrackId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = 1,
                            TrackName = "Entity Framework Core"
                        },
                        new
                        {
                            TrackId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = 2,
                            TrackName = "Flutter"
                        });
                });

            modelBuilder.Entity("Drill08.Entities.Enrollment", b =>
                {
                    b.HasOne("Drill08.Entities.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Drill08.Entities.TrainingTrack", "TrainingTrack")
                        .WithMany("Enrollments")
                        .HasForeignKey("TrainingTrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("TrainingTrack");
                });

            modelBuilder.Entity("Drill08.Entities.Payment", b =>
                {
                    b.HasOne("Drill08.Entities.PaymentSummary", "PaymentSummary")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentSummaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentSummary");
                });

            modelBuilder.Entity("Drill08.Entities.PaymentSummary", b =>
                {
                    b.HasOne("Drill08.Entities.Enrollment", "Enrollment")
                        .WithOne("PaymentSummary")
                        .HasForeignKey("Drill08.Entities.PaymentSummary", "EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("Drill08.Entities.StudentProfile", b =>
                {
                    b.HasOne("Drill08.Entities.Student", "Student")
                        .WithOne("StudentProfile")
                        .HasForeignKey("Drill08.Entities.StudentProfile", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Drill08.Entities.TrainingTrack", b =>
                {
                    b.HasOne("Drill08.Entities.Instructor", "Instructor")
                        .WithMany("TrainingTracks")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("Drill08.Entities.Enrollment", b =>
                {
                    b.Navigation("PaymentSummary");
                });

            modelBuilder.Entity("Drill08.Entities.Instructor", b =>
                {
                    b.Navigation("TrainingTracks");
                });

            modelBuilder.Entity("Drill08.Entities.PaymentSummary", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Drill08.Entities.Student", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("Drill08.Entities.TrainingTrack", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
