// <auto-generated />
using System;
using Drill03.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Drill03.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260722171817_AddInstructorsAndTracks")]
    partial class AddInstructorsAndTracks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Drill03.Entities.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sama@gmail.com",
                            FullName = "Sama Samy"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sara@gmail.com",
                            FullName = "Sara Mohamed"
                        });
                });

            modelBuilder.Entity("Drill03.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "rowida@gmail.com",
                            FullName = "Rowida Gamal",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("Drill03.Entities.StudentProfile", b =>
                {
                    b.Property<int>("NationalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NationalId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmergencyPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("NationalId");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("StudentProfiles");

                    b.HasData(
                        new
                        {
                            NationalId = 123456789,
                            Address = "Cairo",
                            DateOfBirth = new DateTime(2005, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmergencyPhone = "01122055628",
                            StudentId = 1
                        });
                });

            modelBuilder.Entity("Drill03.Entities.TrainingTrack", b =>
                {
                    b.Property<int>("TrackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrackId"));

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("TrackName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrackId");

                    b.HasIndex("InstructorId");

                    b.ToTable("TrainingTracks");

                    b.HasData(
                        new
                        {
                            TrackId = 1,
                            InstructorId = 1,
                            TrackName = "ASP.NET Core"
                        },
                        new
                        {
                            TrackId = 2,
                            InstructorId = 1,
                            TrackName = "Entity Framework Core"
                        },
                        new
                        {
                            TrackId = 3,
                            InstructorId = 2,
                            TrackName = "Flutter"
                        });
                });

            modelBuilder.Entity("Drill03.Entities.StudentProfile", b =>
                {
                    b.HasOne("Drill03.Entities.Student", "Student")
                        .WithOne("StudentProfile")
                        .HasForeignKey("Drill03.Entities.StudentProfile", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Drill03.Entities.TrainingTrack", b =>
                {
                    b.HasOne("Drill03.Entities.Instructor", "Instructor")
                        .WithMany("TrainingTracks")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("Drill03.Entities.Instructor", b =>
                {
                    b.Navigation("TrainingTracks");
                });

            modelBuilder.Entity("Drill03.Entities.Student", b =>
                {
                    b.Navigation("StudentProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
